apps/funcionarios/urls.py
from django.urls import path
from .views import (
    FuncionariosList,
    FuncionariosEdit,
    FuncionariosDelete,
    FuncionarioCreate,
)

urlpatterns = [
    path('', FuncionariosList.as_view(), name="list_funcionarios"),
    path('editar/<int:pk>', FuncionariosEdit.as_view(), name="update_funcionario"),
    path('deletar/<int:pk>', FuncionariosDelete.as_view(), name="delete_funcionario"),
    path('novo/', FuncionarioCreate.as_view(), name="create_funcionario"),
]

gestao_rh/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    # DJANGO APPS
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    
    # CUSTOM APPS
    path('', include('apps.core.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('documentos/', include('apps.documentos.urls')),
    path('empresas/', include('apps.empresas.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('horas-extras/', include('apps.registro_hora_extra.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/documentos/models.py
from django.db import models
from django.shortcuts import reverse

from apps.funcionarios.models import Funcionario

class Documento(models.Model):
  titulo = models.CharField(max_length=100)
  pertence = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
  arquivo = models.FileField(upload_to='documentos')

  def get_absolute_url(self):
      return reverse("update_funcionario", args=[self.pertence.id])
  

  def __str__(self):
      return self.titulo

apps/funcionarios/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models import Sum

from apps.departamentos.models import Departamento
from apps.empresas.models import Empresa

class Funcionario(models.Model):
  nome = models.CharField(max_length=100)
  user = models.OneToOneField(User, on_delete=models.PROTECT)
  departamentos = models.ManyToManyField(Departamento)
  empresa = models.ForeignKey(Empresa, on_delete=models.PROTECT, null=True, blank=True)

  def get_absolute_url(self):
      return reverse("list_funcionarios")

  @property
  def total_horas_extras(self):
    """
    Returns the sum of all employee's overtime
    """
    return self.registrohoraextra_set.all().aggregate(Sum('horas'))['horas__sum']

  def __str__(self):
      return self.nome
  

apps/registro_hora_extra/models.py
from django.db import models
from django.urls import reverse

from apps.funcionarios.models import Funcionario


class RegistroHoraExtra(models.Model):
  motivo = models.CharField(max_length=100)
  funcionario = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
  horas = models.DecimalField(max_digits=5, decimal_places=2)

  def get_absolute_url(self):
    return reverse('update_hora_extra', args=[self.id])

  def __str__(self):
      return self.motivo
  

apps/funcionarios/views.py
from django.contrib.auth.models import User
from django.views.generic import (
  ListView,
  UpdateView,
  DeleteView,
  CreateView
)
from django.urls import reverse_lazy

from .models import Funcionario

class FuncionariosList(ListView):
  model = Funcionario

  def get_queryset(self):
    empresa_logada = self.request.user.funcionario.empresa
    return self.model.objects.filter(empresa=empresa_logada)

class FuncionariosEdit(UpdateView):
  model = Funcionario
  fields = ['nome', 'departamentos']

class FuncionariosDelete(DeleteView):
  model = Funcionario
  success_url = reverse_lazy('list_funcionarios')

class FuncionarioCreate(CreateView):
  model = Funcionario
  fields = ['nome', 'departamentos']

  def form_valid(self, form):
    # Salvando funcionário temporariamente em memória
    funcionario = form.save(commit=False)

    """
    Coletando campos faltantes do model
    contidos na sessão
    """
    username = funcionario.nome.split(' ')[0] + ' ' + funcionario.nome.split(' ')[1]
    funcionario.empresa = self.request.user.funcionario.empresa
    funcionario.user = User.objects.create(username=username)
    # armazenando funcionário no banco
    funcionario.save()
    
    return super(FuncionarioCreate, self).form_valid(form)

apps/funcionarios/templates/funcionarios/funcionario_confirm_delete.html
{% extends 'base.html' %}

{% block main %}
  <form method="post">
    {% csrf_token %}

    <h1>Tem certeza de que deseja deletar o funcionário {{ object }}?</h1>

    {{ form }}

    <button type="submit" class="btn btn-danger">Confirmar</button>
  </form>
{% endblock main %}

apps/funcionarios/templates/funcionarios/funcionario_form.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %}

  <form method="post">
    {% csrf_token %}
    
    {{  form | bootstrap }}
    
    <button class="btn btn-primary mt-3" type="submit">Salvar</button>
  </form>

  {% if object.documento_set %}

    <ul class="list-group mt-5">

      {% for doc in object.documento_set.all %}
        
      <a href="{{ doc.arquivo.url }}">
        <li class="list-group-item">
          {{ doc }}
        </li>
      </a>
      
      {% endfor %}

    </ul>

  {% endif %}
    
  {% if object %}
    
    <a class="btn btn-primary mt-3" href="{% url 'create_documento' object.id %}">Adicionar Documento</a> 
    
  {% endif %}

  {% if object.registrohoraextra_set %}

    <ul class="list-group mt-5">

      {% for hora_extra in object.registrohoraextra_set.all %}
        <a href="{% url 'update_hora_extra_funcionario' hora_extra.id %}">
          <li class="list-group-item">
            {{ hora_extra.motivo }} | {{ hora_extra.horas }}
          </li>
        </a>

      {% endfor %}

    </ul>

    <h3>Total de horas extras: {{ object.total_horas_extras }}</h3>

  {% endif %}

  <a class="btn btn-primary mt-3" href="{% url 'create_hora_extra' %}">Lançar Hora Extra</a> 
  
  <button class="btn btn-outline-dark" onclick="window.history.back()">Voltar</button>

  {% endblock main %}

apps/funcionarios/templates/funcionarios/funcionario_list.html
{% extends 'base.html' %}

{% block main %}
  
  List
  <ul>
    {% for funcionario in object_list %}
      <li>
        <a href="{% url 'update_funcionario' funcionario.id %}">{{ funcionario }}</a>
        &nbsp;
        <a class="btn btn-danger" href="{% url 'delete_funcionario' funcionario.id %}">Deletar</a>
      </li>
    {% endfor %}
  </ul>

  <a class="btn btn-info" href=" {% url 'create_funcionario' %} ">Novo Funcionráio</a>

{% endblock main%}